from __future__ import annotations

from enum import Enum


M6_SCHEMA_VERSION = 1
M6_PROPOSAL_BUDGET = 5
PROPOSAL_ORIGIN = "BENCHMARK_INFORMED_DIAGNOSTIC"


class DiagnosticCause(str, Enum):
    INPUT_SEMANTIC_MISSING = "INPUT_SEMANTIC_MISSING"
    EFFECT_SEMANTIC_MISSING = "EFFECT_SEMANTIC_MISSING"
    WRAPPER_OR_LIBRARY_FLOW_MISSING = "WRAPPER_OR_LIBRARY_FLOW_MISSING"
    FIELD_OR_STATE_FLOW_MISSING = "FIELD_OR_STATE_FLOW_MISSING"
    FRAMEWORK_OR_CALLBACK_RELATION_MISSING = "FRAMEWORK_OR_CALLBACK_RELATION_MISSING"
    MULTIPLE_SEMANTIC_RELATIONS_REQUIRED = "MULTIPLE_SEMANTIC_RELATIONS_REQUIRED"
    NOT_EXPRESSIBLE_BY_V11 = "NOT_EXPRESSIBLE_BY_V11"
    NOT_A_SEMANTIC_GAP = "NOT_A_SEMANTIC_GAP"
    UNCERTAIN = "UNCERTAIN"


class FailureReason(str, Enum):
    NO_RECOVERY_AFTER_VALID_PROPOSALS = "NO_RECOVERY_AFTER_VALID_PROPOSALS"
    GATE_BLOCKED = "GATE_BLOCKED"
    PATH_BUILDER_LIMITATION = "PATH_BUILDER_LIMITATION"
    ENTITY_MAPPING_LIMITATION = "ENTITY_MAPPING_LIMITATION"
    CODEQL_TOOL_LIMITATION = "CODEQL_TOOL_LIMITATION"
    INSUFFICIENT_PROGRAM_EVIDENCE = "INSUFFICIENT_PROGRAM_EVIDENCE"
    NOT_EXPRESSIBLE_BY_CURRENT_PROPOSAL_TYPES = "NOT_EXPRESSIBLE_BY_CURRENT_PROPOSAL_TYPES"
    NOT_SEMANTIC_GAP = "NOT_SEMANTIC_GAP"
    INFRASTRUCTURE_FAILURE = "INFRASTRUCTURE_FAILURE"
    UNCERTAIN = "UNCERTAIN"
